project:
  type: website
  output-dir: docs

website:
  title: "Marian Melnyk"
  navbar:
    background: secondary
    foreground: info
    search: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - talks.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

